### ISSUE TITLE
Angular component not available on 8.2.4

### ISSUE THREAD

**Issue by jfvilasAbanca** [bennymeg/ngx-embedded-media#3]
Hi.

I've installed the component via 'npm i ngx-embedded-media', but only source code has been installed in my node_modules. Is it possible to have a pre-built component as it occurred in 8.2.3?

thanks.

**Comment by lautarojgarcia177** [comment]
Same here

**Comment by bennymeg** [comment]
Sorry for the late response, I did not got a notification.
I'll check soon, and update.

**Comment by bennymeg** [comment]
fixed in v8.3.0
